sudo: required
services:
  - docker

before_install:
  - docker build -t jaredwmitchell/docker-react -f Dockerfile.dev .

script:
  - docker run jaredwmitchell/docker-react npm run test -- --coverage
  